---
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  labels:
    {{- include "llm-cost-monitor.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.secrets.annotations | nindent 4 }}
type: Opaque
data:
  {{- if .Values.providers.openai.enabled }}
  openai-api-key: {{ required "openai.apiKey required when openai.enabled=true" .Values.providers.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.providers.anthropic.enabled }}
  anthropic-api-key: {{ required "anthropic.apiKey required when anthropic.enabled=true" .Values.providers.anthropic.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
