---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-cost-monitor.fullname" . }}
  labels:
    {{- include "llm-cost-monitor.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-cost-monitor.selectorLabels" . | nindent 4 }}
