---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-cost-monitor.serviceAccountName" . }}
  labels:
    {{- include "llm-cost-monitor.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.providers.bedrock.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.providers.bedrock.iamRoleArn }}
    {{- end }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
