---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: llm-cost-alerts
spec:
  groups:
  - name: llm-cost-monitor
    rules:
    - alert: HighLLMCost
      expr: sum by (provider) (llm_cost_usd) > 100
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "High LLM cost for {{ $labels.provider }}"
        description: "Current cost is {{ $value }} USD"

    - alert: RateLimitApproaching
      expr: rate(llm_requests_total[5m]) > 100
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High request rate to LLM APIs"
