services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./dashboards.yml/etc/grafana/provisioning/dashboards.yml
      - ./datasource.yml/etc/grafana/provisioning/datasources/datasource.yml
      - ../../grafana:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  llm_cost_evaluator:
    image: teaglebuilt/llm_cost_evaluator:v1.0.0
    container_name: llm_cost_evaluator
    restart: unless-stopped
    env:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 9943:9443
